package com.crm.domain.crm;

import java.io.Serializable;

public class User2 implements Serializable {
	/** 用户id */
	private Integer id;

	/** 用户代码 */
	private String userCode;

	/** 名字 */
	private String userName;

	/** 英文名字 */
	private String englishName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table tb_user
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_user.id
	 *
	 * @return the value of tb_user.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_user.id
	 *
	 * @param id
	 *            the value for tb_user.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_user.user_code
	 *
	 * @return the value of tb_user.user_code
	 *
	 * @mbggenerated
	 */
	public String getUserCode() {
		return userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_user.user_code
	 *
	 * @param userCode
	 *            the value for tb_user.user_code
	 *
	 * @mbggenerated
	 */
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_user.user_name
	 *
	 * @return the value of tb_user.user_name
	 *
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_user.user_name
	 *
	 * @param userName
	 *            the value for tb_user.user_name
	 *
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_user.english_name
	 *
	 * @return the value of tb_user.english_name
	 *
	 * @mbggenerated
	 */
	public String getEnglishName() {
		return englishName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_user.english_name
	 *
	 * @param englishName
	 *            the value for tb_user.english_name
	 *
	 * @mbggenerated
	 */
	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

}