package com.crm.domain.crm;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.crm.util.mybatis.plugin.Limit;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    private Limit limit;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Limit limit) {
        this.limit = limit;
    }

    public Limit getLimit() {
        return this.limit;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(Criterion criterion) {
            if (criterion == null) {
                throw new RuntimeException("Value for criterion cannot be null");
            }
            criteria.add(criterion);
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserCodeIsNull() {
            addCriterion("user_code is null");
            return (Criteria) this;
        }

        public Criteria andUserCodeIsNotNull() {
            addCriterion("user_code is not null");
            return (Criteria) this;
        }

        public Criteria andUserCodeEqualTo(String value) {
            addCriterion("user_code =", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotEqualTo(String value) {
            addCriterion("user_code <>", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeGreaterThan(String value) {
            addCriterion("user_code >", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("user_code >=", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLessThan(String value) {
            addCriterion("user_code <", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLessThanOrEqualTo(String value) {
            addCriterion("user_code <=", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLike(String value) {
            addCriterion("user_code like", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotLike(String value) {
            addCriterion("user_code not like", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeIn(List<String> values) {
            addCriterion("user_code in", values, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotIn(List<String> values) {
            addCriterion("user_code not in", values, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeBetween(String value1, String value2) {
            addCriterion("user_code between", value1, value2, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotBetween(String value1, String value2) {
            addCriterion("user_code not between", value1, value2, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameIsNull() {
            addCriterion("english_name is null");
            return (Criteria) this;
        }

        public Criteria andEnglishNameIsNotNull() {
            addCriterion("english_name is not null");
            return (Criteria) this;
        }

        public Criteria andEnglishNameEqualTo(String value) {
            addCriterion("english_name =", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotEqualTo(String value) {
            addCriterion("english_name <>", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameGreaterThan(String value) {
            addCriterion("english_name >", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameGreaterThanOrEqualTo(String value) {
            addCriterion("english_name >=", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameLessThan(String value) {
            addCriterion("english_name <", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameLessThanOrEqualTo(String value) {
            addCriterion("english_name <=", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameLike(String value) {
            addCriterion("english_name like", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotLike(String value) {
            addCriterion("english_name not like", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameIn(List<String> values) {
            addCriterion("english_name in", values, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotIn(List<String> values) {
            addCriterion("english_name not in", values, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameBetween(String value1, String value2) {
            addCriterion("english_name between", value1, value2, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotBetween(String value1, String value2) {
            addCriterion("english_name not between", value1, value2, "englishName");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(Integer value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(Integer value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(Integer value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(Integer value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(Integer value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<Integer> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<Integer> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(Integer value1, Integer value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(Integer value1, Integer value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andPositionTitleIsNull() {
            addCriterion("position_title is null");
            return (Criteria) this;
        }

        public Criteria andPositionTitleIsNotNull() {
            addCriterion("position_title is not null");
            return (Criteria) this;
        }

        public Criteria andPositionTitleEqualTo(String value) {
            addCriterion("position_title =", value, "positionTitle");
            return (Criteria) this;
        }

        public Criteria andPositionTitleNotEqualTo(String value) {
            addCriterion("position_title <>", value, "positionTitle");
            return (Criteria) this;
        }

        public Criteria andPositionTitleGreaterThan(String value) {
            addCriterion("position_title >", value, "positionTitle");
            return (Criteria) this;
        }

        public Criteria andPositionTitleGreaterThanOrEqualTo(String value) {
            addCriterion("position_title >=", value, "positionTitle");
            return (Criteria) this;
        }

        public Criteria andPositionTitleLessThan(String value) {
            addCriterion("position_title <", value, "positionTitle");
            return (Criteria) this;
        }

        public Criteria andPositionTitleLessThanOrEqualTo(String value) {
            addCriterion("position_title <=", value, "positionTitle");
            return (Criteria) this;
        }

        public Criteria andPositionTitleLike(String value) {
            addCriterion("position_title like", value, "positionTitle");
            return (Criteria) this;
        }

        public Criteria andPositionTitleNotLike(String value) {
            addCriterion("position_title not like", value, "positionTitle");
            return (Criteria) this;
        }

        public Criteria andPositionTitleIn(List<String> values) {
            addCriterion("position_title in", values, "positionTitle");
            return (Criteria) this;
        }

        public Criteria andPositionTitleNotIn(List<String> values) {
            addCriterion("position_title not in", values, "positionTitle");
            return (Criteria) this;
        }

        public Criteria andPositionTitleBetween(String value1, String value2) {
            addCriterion("position_title between", value1, value2, "positionTitle");
            return (Criteria) this;
        }

        public Criteria andPositionTitleNotBetween(String value1, String value2) {
            addCriterion("position_title not between", value1, value2, "positionTitle");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNull() {
            addCriterion("mobile_phone is null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNotNull() {
            addCriterion("mobile_phone is not null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneEqualTo(String value) {
            addCriterion("mobile_phone =", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotEqualTo(String value) {
            addCriterion("mobile_phone <>", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThan(String value) {
            addCriterion("mobile_phone >", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_phone >=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThan(String value) {
            addCriterion("mobile_phone <", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("mobile_phone <=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLike(String value) {
            addCriterion("mobile_phone like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotLike(String value) {
            addCriterion("mobile_phone not like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIn(List<String> values) {
            addCriterion("mobile_phone in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotIn(List<String> values) {
            addCriterion("mobile_phone not in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneBetween(String value1, String value2) {
            addCriterion("mobile_phone between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("mobile_phone not between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andTelePhoneIsNull() {
            addCriterion("tele_phone is null");
            return (Criteria) this;
        }

        public Criteria andTelePhoneIsNotNull() {
            addCriterion("tele_phone is not null");
            return (Criteria) this;
        }

        public Criteria andTelePhoneEqualTo(String value) {
            addCriterion("tele_phone =", value, "telePhone");
            return (Criteria) this;
        }

        public Criteria andTelePhoneNotEqualTo(String value) {
            addCriterion("tele_phone <>", value, "telePhone");
            return (Criteria) this;
        }

        public Criteria andTelePhoneGreaterThan(String value) {
            addCriterion("tele_phone >", value, "telePhone");
            return (Criteria) this;
        }

        public Criteria andTelePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("tele_phone >=", value, "telePhone");
            return (Criteria) this;
        }

        public Criteria andTelePhoneLessThan(String value) {
            addCriterion("tele_phone <", value, "telePhone");
            return (Criteria) this;
        }

        public Criteria andTelePhoneLessThanOrEqualTo(String value) {
            addCriterion("tele_phone <=", value, "telePhone");
            return (Criteria) this;
        }

        public Criteria andTelePhoneLike(String value) {
            addCriterion("tele_phone like", value, "telePhone");
            return (Criteria) this;
        }

        public Criteria andTelePhoneNotLike(String value) {
            addCriterion("tele_phone not like", value, "telePhone");
            return (Criteria) this;
        }

        public Criteria andTelePhoneIn(List<String> values) {
            addCriterion("tele_phone in", values, "telePhone");
            return (Criteria) this;
        }

        public Criteria andTelePhoneNotIn(List<String> values) {
            addCriterion("tele_phone not in", values, "telePhone");
            return (Criteria) this;
        }

        public Criteria andTelePhoneBetween(String value1, String value2) {
            addCriterion("tele_phone between", value1, value2, "telePhone");
            return (Criteria) this;
        }

        public Criteria andTelePhoneNotBetween(String value1, String value2) {
            addCriterion("tele_phone not between", value1, value2, "telePhone");
            return (Criteria) this;
        }

        public Criteria andTelePhone2IsNull() {
            addCriterion("tele_phone2 is null");
            return (Criteria) this;
        }

        public Criteria andTelePhone2IsNotNull() {
            addCriterion("tele_phone2 is not null");
            return (Criteria) this;
        }

        public Criteria andTelePhone2EqualTo(String value) {
            addCriterion("tele_phone2 =", value, "telePhone2");
            return (Criteria) this;
        }

        public Criteria andTelePhone2NotEqualTo(String value) {
            addCriterion("tele_phone2 <>", value, "telePhone2");
            return (Criteria) this;
        }

        public Criteria andTelePhone2GreaterThan(String value) {
            addCriterion("tele_phone2 >", value, "telePhone2");
            return (Criteria) this;
        }

        public Criteria andTelePhone2GreaterThanOrEqualTo(String value) {
            addCriterion("tele_phone2 >=", value, "telePhone2");
            return (Criteria) this;
        }

        public Criteria andTelePhone2LessThan(String value) {
            addCriterion("tele_phone2 <", value, "telePhone2");
            return (Criteria) this;
        }

        public Criteria andTelePhone2LessThanOrEqualTo(String value) {
            addCriterion("tele_phone2 <=", value, "telePhone2");
            return (Criteria) this;
        }

        public Criteria andTelePhone2Like(String value) {
            addCriterion("tele_phone2 like", value, "telePhone2");
            return (Criteria) this;
        }

        public Criteria andTelePhone2NotLike(String value) {
            addCriterion("tele_phone2 not like", value, "telePhone2");
            return (Criteria) this;
        }

        public Criteria andTelePhone2In(List<String> values) {
            addCriterion("tele_phone2 in", values, "telePhone2");
            return (Criteria) this;
        }

        public Criteria andTelePhone2NotIn(List<String> values) {
            addCriterion("tele_phone2 not in", values, "telePhone2");
            return (Criteria) this;
        }

        public Criteria andTelePhone2Between(String value1, String value2) {
            addCriterion("tele_phone2 between", value1, value2, "telePhone2");
            return (Criteria) this;
        }

        public Criteria andTelePhone2NotBetween(String value1, String value2) {
            addCriterion("tele_phone2 not between", value1, value2, "telePhone2");
            return (Criteria) this;
        }

        public Criteria andDirectNoIsNull() {
            addCriterion("direct_no is null");
            return (Criteria) this;
        }

        public Criteria andDirectNoIsNotNull() {
            addCriterion("direct_no is not null");
            return (Criteria) this;
        }

        public Criteria andDirectNoEqualTo(String value) {
            addCriterion("direct_no =", value, "directNo");
            return (Criteria) this;
        }

        public Criteria andDirectNoNotEqualTo(String value) {
            addCriterion("direct_no <>", value, "directNo");
            return (Criteria) this;
        }

        public Criteria andDirectNoGreaterThan(String value) {
            addCriterion("direct_no >", value, "directNo");
            return (Criteria) this;
        }

        public Criteria andDirectNoGreaterThanOrEqualTo(String value) {
            addCriterion("direct_no >=", value, "directNo");
            return (Criteria) this;
        }

        public Criteria andDirectNoLessThan(String value) {
            addCriterion("direct_no <", value, "directNo");
            return (Criteria) this;
        }

        public Criteria andDirectNoLessThanOrEqualTo(String value) {
            addCriterion("direct_no <=", value, "directNo");
            return (Criteria) this;
        }

        public Criteria andDirectNoLike(String value) {
            addCriterion("direct_no like", value, "directNo");
            return (Criteria) this;
        }

        public Criteria andDirectNoNotLike(String value) {
            addCriterion("direct_no not like", value, "directNo");
            return (Criteria) this;
        }

        public Criteria andDirectNoIn(List<String> values) {
            addCriterion("direct_no in", values, "directNo");
            return (Criteria) this;
        }

        public Criteria andDirectNoNotIn(List<String> values) {
            addCriterion("direct_no not in", values, "directNo");
            return (Criteria) this;
        }

        public Criteria andDirectNoBetween(String value1, String value2) {
            addCriterion("direct_no between", value1, value2, "directNo");
            return (Criteria) this;
        }

        public Criteria andDirectNoNotBetween(String value1, String value2) {
            addCriterion("direct_no not between", value1, value2, "directNo");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andQqIsNull() {
            addCriterion("qq is null");
            return (Criteria) this;
        }

        public Criteria andQqIsNotNull() {
            addCriterion("qq is not null");
            return (Criteria) this;
        }

        public Criteria andQqEqualTo(String value) {
            addCriterion("qq =", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotEqualTo(String value) {
            addCriterion("qq <>", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThan(String value) {
            addCriterion("qq >", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThanOrEqualTo(String value) {
            addCriterion("qq >=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThan(String value) {
            addCriterion("qq <", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThanOrEqualTo(String value) {
            addCriterion("qq <=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLike(String value) {
            addCriterion("qq like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotLike(String value) {
            addCriterion("qq not like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqIn(List<String> values) {
            addCriterion("qq in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotIn(List<String> values) {
            addCriterion("qq not in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqBetween(String value1, String value2) {
            addCriterion("qq between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotBetween(String value1, String value2) {
            addCriterion("qq not between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andWeixinIsNull() {
            addCriterion("weixin is null");
            return (Criteria) this;
        }

        public Criteria andWeixinIsNotNull() {
            addCriterion("weixin is not null");
            return (Criteria) this;
        }

        public Criteria andWeixinEqualTo(String value) {
            addCriterion("weixin =", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinNotEqualTo(String value) {
            addCriterion("weixin <>", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinGreaterThan(String value) {
            addCriterion("weixin >", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinGreaterThanOrEqualTo(String value) {
            addCriterion("weixin >=", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinLessThan(String value) {
            addCriterion("weixin <", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinLessThanOrEqualTo(String value) {
            addCriterion("weixin <=", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinLike(String value) {
            addCriterion("weixin like", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinNotLike(String value) {
            addCriterion("weixin not like", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinIn(List<String> values) {
            addCriterion("weixin in", values, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinNotIn(List<String> values) {
            addCriterion("weixin not in", values, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinBetween(String value1, String value2) {
            addCriterion("weixin between", value1, value2, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinNotBetween(String value1, String value2) {
            addCriterion("weixin not between", value1, value2, "weixin");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNull() {
            addCriterion("avatar is null");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNotNull() {
            addCriterion("avatar is not null");
            return (Criteria) this;
        }

        public Criteria andAvatarEqualTo(String value) {
            addCriterion("avatar =", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotEqualTo(String value) {
            addCriterion("avatar <>", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThan(String value) {
            addCriterion("avatar >", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThanOrEqualTo(String value) {
            addCriterion("avatar >=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThan(String value) {
            addCriterion("avatar <", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThanOrEqualTo(String value) {
            addCriterion("avatar <=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLike(String value) {
            addCriterion("avatar like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotLike(String value) {
            addCriterion("avatar not like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarIn(List<String> values) {
            addCriterion("avatar in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotIn(List<String> values) {
            addCriterion("avatar not in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarBetween(String value1, String value2) {
            addCriterion("avatar between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotBetween(String value1, String value2) {
            addCriterion("avatar not between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDermaIsNull() {
            addCriterion("derma is null");
            return (Criteria) this;
        }

        public Criteria andDermaIsNotNull() {
            addCriterion("derma is not null");
            return (Criteria) this;
        }

        public Criteria andDermaEqualTo(Integer value) {
            addCriterion("derma =", value, "derma");
            return (Criteria) this;
        }

        public Criteria andDermaNotEqualTo(Integer value) {
            addCriterion("derma <>", value, "derma");
            return (Criteria) this;
        }

        public Criteria andDermaGreaterThan(Integer value) {
            addCriterion("derma >", value, "derma");
            return (Criteria) this;
        }

        public Criteria andDermaGreaterThanOrEqualTo(Integer value) {
            addCriterion("derma >=", value, "derma");
            return (Criteria) this;
        }

        public Criteria andDermaLessThan(Integer value) {
            addCriterion("derma <", value, "derma");
            return (Criteria) this;
        }

        public Criteria andDermaLessThanOrEqualTo(Integer value) {
            addCriterion("derma <=", value, "derma");
            return (Criteria) this;
        }

        public Criteria andDermaIn(List<Integer> values) {
            addCriterion("derma in", values, "derma");
            return (Criteria) this;
        }

        public Criteria andDermaNotIn(List<Integer> values) {
            addCriterion("derma not in", values, "derma");
            return (Criteria) this;
        }

        public Criteria andDermaBetween(Integer value1, Integer value2) {
            addCriterion("derma between", value1, value2, "derma");
            return (Criteria) this;
        }

        public Criteria andDermaNotBetween(Integer value1, Integer value2) {
            addCriterion("derma not between", value1, value2, "derma");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Long value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Long value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Long value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Long value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Long> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Long> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Long value1, Long value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(Long value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(Long value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(Long value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(Long value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<Long> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<Long> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(Long value1, Long value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andDimissionOperatorIsNull() {
            addCriterion("dimission_operator is null");
            return (Criteria) this;
        }

        public Criteria andDimissionOperatorIsNotNull() {
            addCriterion("dimission_operator is not null");
            return (Criteria) this;
        }

        public Criteria andDimissionOperatorEqualTo(Long value) {
            addCriterion("dimission_operator =", value, "dimissionOperator");
            return (Criteria) this;
        }

        public Criteria andDimissionOperatorNotEqualTo(Long value) {
            addCriterion("dimission_operator <>", value, "dimissionOperator");
            return (Criteria) this;
        }

        public Criteria andDimissionOperatorGreaterThan(Long value) {
            addCriterion("dimission_operator >", value, "dimissionOperator");
            return (Criteria) this;
        }

        public Criteria andDimissionOperatorGreaterThanOrEqualTo(Long value) {
            addCriterion("dimission_operator >=", value, "dimissionOperator");
            return (Criteria) this;
        }

        public Criteria andDimissionOperatorLessThan(Long value) {
            addCriterion("dimission_operator <", value, "dimissionOperator");
            return (Criteria) this;
        }

        public Criteria andDimissionOperatorLessThanOrEqualTo(Long value) {
            addCriterion("dimission_operator <=", value, "dimissionOperator");
            return (Criteria) this;
        }

        public Criteria andDimissionOperatorIn(List<Long> values) {
            addCriterion("dimission_operator in", values, "dimissionOperator");
            return (Criteria) this;
        }

        public Criteria andDimissionOperatorNotIn(List<Long> values) {
            addCriterion("dimission_operator not in", values, "dimissionOperator");
            return (Criteria) this;
        }

        public Criteria andDimissionOperatorBetween(Long value1, Long value2) {
            addCriterion("dimission_operator between", value1, value2, "dimissionOperator");
            return (Criteria) this;
        }

        public Criteria andDimissionOperatorNotBetween(Long value1, Long value2) {
            addCriterion("dimission_operator not between", value1, value2, "dimissionOperator");
            return (Criteria) this;
        }

        public Criteria andDimissionOperateTimeIsNull() {
            addCriterion("dimission_operate_time is null");
            return (Criteria) this;
        }

        public Criteria andDimissionOperateTimeIsNotNull() {
            addCriterion("dimission_operate_time is not null");
            return (Criteria) this;
        }

        public Criteria andDimissionOperateTimeEqualTo(Date value) {
            addCriterion("dimission_operate_time =", value, "dimissionOperateTime");
            return (Criteria) this;
        }

        public Criteria andDimissionOperateTimeNotEqualTo(Date value) {
            addCriterion("dimission_operate_time <>", value, "dimissionOperateTime");
            return (Criteria) this;
        }

        public Criteria andDimissionOperateTimeGreaterThan(Date value) {
            addCriterion("dimission_operate_time >", value, "dimissionOperateTime");
            return (Criteria) this;
        }

        public Criteria andDimissionOperateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("dimission_operate_time >=", value, "dimissionOperateTime");
            return (Criteria) this;
        }

        public Criteria andDimissionOperateTimeLessThan(Date value) {
            addCriterion("dimission_operate_time <", value, "dimissionOperateTime");
            return (Criteria) this;
        }

        public Criteria andDimissionOperateTimeLessThanOrEqualTo(Date value) {
            addCriterion("dimission_operate_time <=", value, "dimissionOperateTime");
            return (Criteria) this;
        }

        public Criteria andDimissionOperateTimeIn(List<Date> values) {
            addCriterion("dimission_operate_time in", values, "dimissionOperateTime");
            return (Criteria) this;
        }

        public Criteria andDimissionOperateTimeNotIn(List<Date> values) {
            addCriterion("dimission_operate_time not in", values, "dimissionOperateTime");
            return (Criteria) this;
        }

        public Criteria andDimissionOperateTimeBetween(Date value1, Date value2) {
            addCriterion("dimission_operate_time between", value1, value2, "dimissionOperateTime");
            return (Criteria) this;
        }

        public Criteria andDimissionOperateTimeNotBetween(Date value1, Date value2) {
            addCriterion("dimission_operate_time not between", value1, value2, "dimissionOperateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteOperatorIsNull() {
            addCriterion("delete_operator is null");
            return (Criteria) this;
        }

        public Criteria andDeleteOperatorIsNotNull() {
            addCriterion("delete_operator is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteOperatorEqualTo(Long value) {
            addCriterion("delete_operator =", value, "deleteOperator");
            return (Criteria) this;
        }

        public Criteria andDeleteOperatorNotEqualTo(Long value) {
            addCriterion("delete_operator <>", value, "deleteOperator");
            return (Criteria) this;
        }

        public Criteria andDeleteOperatorGreaterThan(Long value) {
            addCriterion("delete_operator >", value, "deleteOperator");
            return (Criteria) this;
        }

        public Criteria andDeleteOperatorGreaterThanOrEqualTo(Long value) {
            addCriterion("delete_operator >=", value, "deleteOperator");
            return (Criteria) this;
        }

        public Criteria andDeleteOperatorLessThan(Long value) {
            addCriterion("delete_operator <", value, "deleteOperator");
            return (Criteria) this;
        }

        public Criteria andDeleteOperatorLessThanOrEqualTo(Long value) {
            addCriterion("delete_operator <=", value, "deleteOperator");
            return (Criteria) this;
        }

        public Criteria andDeleteOperatorIn(List<Long> values) {
            addCriterion("delete_operator in", values, "deleteOperator");
            return (Criteria) this;
        }

        public Criteria andDeleteOperatorNotIn(List<Long> values) {
            addCriterion("delete_operator not in", values, "deleteOperator");
            return (Criteria) this;
        }

        public Criteria andDeleteOperatorBetween(Long value1, Long value2) {
            addCriterion("delete_operator between", value1, value2, "deleteOperator");
            return (Criteria) this;
        }

        public Criteria andDeleteOperatorNotBetween(Long value1, Long value2) {
            addCriterion("delete_operator not between", value1, value2, "deleteOperator");
            return (Criteria) this;
        }

        public Criteria andDeleteOperateTimeIsNull() {
            addCriterion("delete_operate_time is null");
            return (Criteria) this;
        }

        public Criteria andDeleteOperateTimeIsNotNull() {
            addCriterion("delete_operate_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteOperateTimeEqualTo(Date value) {
            addCriterion("delete_operate_time =", value, "deleteOperateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteOperateTimeNotEqualTo(Date value) {
            addCriterion("delete_operate_time <>", value, "deleteOperateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteOperateTimeGreaterThan(Date value) {
            addCriterion("delete_operate_time >", value, "deleteOperateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteOperateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("delete_operate_time >=", value, "deleteOperateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteOperateTimeLessThan(Date value) {
            addCriterion("delete_operate_time <", value, "deleteOperateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteOperateTimeLessThanOrEqualTo(Date value) {
            addCriterion("delete_operate_time <=", value, "deleteOperateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteOperateTimeIn(List<Date> values) {
            addCriterion("delete_operate_time in", values, "deleteOperateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteOperateTimeNotIn(List<Date> values) {
            addCriterion("delete_operate_time not in", values, "deleteOperateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteOperateTimeBetween(Date value1, Date value2) {
            addCriterion("delete_operate_time between", value1, value2, "deleteOperateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteOperateTimeNotBetween(Date value1, Date value2) {
            addCriterion("delete_operate_time not between", value1, value2, "deleteOperateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table tb_user
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table tb_user
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private boolean orListValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        public Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }

        public Criterion(List<Criterion> listCriterion) {
            super();
            this.value = listCriterion;
            this.orListValue = true;
        }

        public boolean isOrListValue() {
            return orListValue;
        }
    }
}