package com.crm.dao.ho.loginsource.mapper;

import com.crm.domain.ho.LoginSource;
import com.crm.domain.ho.LoginSourceExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface LoginSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_source
     *
     * @mbggenerated
     */
    int countByExample(LoginSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_source
     *
     * @mbggenerated
     */
    int deleteByExample(LoginSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_source
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_source
     *
     * @mbggenerated
     */
    int insert(LoginSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_source
     *
     * @mbggenerated
     */
    int insertSelective(LoginSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_source
     *
     * @mbggenerated
     */
    List<LoginSource> selectByExample(LoginSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_source
     *
     * @mbggenerated
     */
    LoginSource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_source
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LoginSource record, @Param("example") LoginSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_source
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LoginSource record, @Param("example") LoginSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LoginSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LoginSource record);
}