package com.crm.domain.backend.survey;

import com.crm.util.mybatis.plugin.Limit;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QuesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    private Limit limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    public QuesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Limit limit) {
        this.limit = limit;
    }

    public Limit getLimit() {
        return this.limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(Criterion criterion) {
            if (criterion == null) {
                throw new RuntimeException("Value for criterion cannot be null");
            }
            criteria.add(criterion);
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuesIdIsNull() {
            addCriterion("ques_id is null");
            return (Criteria) this;
        }

        public Criteria andQuesIdIsNotNull() {
            addCriterion("ques_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuesIdEqualTo(Long value) {
            addCriterion("ques_id =", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdNotEqualTo(Long value) {
            addCriterion("ques_id <>", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdGreaterThan(Long value) {
            addCriterion("ques_id >", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ques_id >=", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdLessThan(Long value) {
            addCriterion("ques_id <", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdLessThanOrEqualTo(Long value) {
            addCriterion("ques_id <=", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdIn(List<Long> values) {
            addCriterion("ques_id in", values, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdNotIn(List<Long> values) {
            addCriterion("ques_id not in", values, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdBetween(Long value1, Long value2) {
            addCriterion("ques_id between", value1, value2, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdNotBetween(Long value1, Long value2) {
            addCriterion("ques_id not between", value1, value2, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesNameIsNull() {
            addCriterion("ques_name is null");
            return (Criteria) this;
        }

        public Criteria andQuesNameIsNotNull() {
            addCriterion("ques_name is not null");
            return (Criteria) this;
        }

        public Criteria andQuesNameEqualTo(String value) {
            addCriterion("ques_name =", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameNotEqualTo(String value) {
            addCriterion("ques_name <>", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameGreaterThan(String value) {
            addCriterion("ques_name >", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameGreaterThanOrEqualTo(String value) {
            addCriterion("ques_name >=", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameLessThan(String value) {
            addCriterion("ques_name <", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameLessThanOrEqualTo(String value) {
            addCriterion("ques_name <=", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameLike(String value) {
            addCriterion("ques_name like", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameNotLike(String value) {
            addCriterion("ques_name not like", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameIn(List<String> values) {
            addCriterion("ques_name in", values, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameNotIn(List<String> values) {
            addCriterion("ques_name not in", values, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameBetween(String value1, String value2) {
            addCriterion("ques_name between", value1, value2, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameNotBetween(String value1, String value2) {
            addCriterion("ques_name not between", value1, value2, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameIsNull() {
            addCriterion("ques_english_name is null");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameIsNotNull() {
            addCriterion("ques_english_name is not null");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameEqualTo(String value) {
            addCriterion("ques_english_name =", value, "quesEnglishName");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameNotEqualTo(String value) {
            addCriterion("ques_english_name <>", value, "quesEnglishName");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameGreaterThan(String value) {
            addCriterion("ques_english_name >", value, "quesEnglishName");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameGreaterThanOrEqualTo(String value) {
            addCriterion("ques_english_name >=", value, "quesEnglishName");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameLessThan(String value) {
            addCriterion("ques_english_name <", value, "quesEnglishName");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameLessThanOrEqualTo(String value) {
            addCriterion("ques_english_name <=", value, "quesEnglishName");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameLike(String value) {
            addCriterion("ques_english_name like", value, "quesEnglishName");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameNotLike(String value) {
            addCriterion("ques_english_name not like", value, "quesEnglishName");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameIn(List<String> values) {
            addCriterion("ques_english_name in", values, "quesEnglishName");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameNotIn(List<String> values) {
            addCriterion("ques_english_name not in", values, "quesEnglishName");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameBetween(String value1, String value2) {
            addCriterion("ques_english_name between", value1, value2, "quesEnglishName");
            return (Criteria) this;
        }

        public Criteria andQuesEnglishNameNotBetween(String value1, String value2) {
            addCriterion("ques_english_name not between", value1, value2, "quesEnglishName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIsNull() {
            addCriterion("ques_type is null");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIsNotNull() {
            addCriterion("ques_type is not null");
            return (Criteria) this;
        }

        public Criteria andQuesTypeEqualTo(Integer value) {
            addCriterion("ques_type =", value, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNotEqualTo(Integer value) {
            addCriterion("ques_type <>", value, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeGreaterThan(Integer value) {
            addCriterion("ques_type >", value, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ques_type >=", value, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeLessThan(Integer value) {
            addCriterion("ques_type <", value, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeLessThanOrEqualTo(Integer value) {
            addCriterion("ques_type <=", value, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIn(List<Integer> values) {
            addCriterion("ques_type in", values, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNotIn(List<Integer> values) {
            addCriterion("ques_type not in", values, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeBetween(Integer value1, Integer value2) {
            addCriterion("ques_type between", value1, value2, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("ques_type not between", value1, value2, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdIsNull() {
            addCriterion("ques_survey_id is null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdIsNotNull() {
            addCriterion("ques_survey_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdEqualTo(Long value) {
            addCriterion("ques_survey_id =", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdNotEqualTo(Long value) {
            addCriterion("ques_survey_id <>", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdGreaterThan(Long value) {
            addCriterion("ques_survey_id >", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ques_survey_id >=", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdLessThan(Long value) {
            addCriterion("ques_survey_id <", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdLessThanOrEqualTo(Long value) {
            addCriterion("ques_survey_id <=", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdIn(List<Long> values) {
            addCriterion("ques_survey_id in", values, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdNotIn(List<Long> values) {
            addCriterion("ques_survey_id not in", values, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdBetween(Long value1, Long value2) {
            addCriterion("ques_survey_id between", value1, value2, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdNotBetween(Long value1, Long value2) {
            addCriterion("ques_survey_id not between", value1, value2, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdIsNull() {
            addCriterion("ques_type_id is null");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdIsNotNull() {
            addCriterion("ques_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdEqualTo(Long value) {
            addCriterion("ques_type_id =", value, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdNotEqualTo(Long value) {
            addCriterion("ques_type_id <>", value, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdGreaterThan(Long value) {
            addCriterion("ques_type_id >", value, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ques_type_id >=", value, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdLessThan(Long value) {
            addCriterion("ques_type_id <", value, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdLessThanOrEqualTo(Long value) {
            addCriterion("ques_type_id <=", value, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdIn(List<Long> values) {
            addCriterion("ques_type_id in", values, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdNotIn(List<Long> values) {
            addCriterion("ques_type_id not in", values, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdBetween(Long value1, Long value2) {
            addCriterion("ques_type_id between", value1, value2, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdNotBetween(Long value1, Long value2) {
            addCriterion("ques_type_id not between", value1, value2, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesScoreIsNull() {
            addCriterion("ques_score is null");
            return (Criteria) this;
        }

        public Criteria andQuesScoreIsNotNull() {
            addCriterion("ques_score is not null");
            return (Criteria) this;
        }

        public Criteria andQuesScoreEqualTo(Integer value) {
            addCriterion("ques_score =", value, "quesScore");
            return (Criteria) this;
        }

        public Criteria andQuesScoreNotEqualTo(Integer value) {
            addCriterion("ques_score <>", value, "quesScore");
            return (Criteria) this;
        }

        public Criteria andQuesScoreGreaterThan(Integer value) {
            addCriterion("ques_score >", value, "quesScore");
            return (Criteria) this;
        }

        public Criteria andQuesScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("ques_score >=", value, "quesScore");
            return (Criteria) this;
        }

        public Criteria andQuesScoreLessThan(Integer value) {
            addCriterion("ques_score <", value, "quesScore");
            return (Criteria) this;
        }

        public Criteria andQuesScoreLessThanOrEqualTo(Integer value) {
            addCriterion("ques_score <=", value, "quesScore");
            return (Criteria) this;
        }

        public Criteria andQuesScoreIn(List<Integer> values) {
            addCriterion("ques_score in", values, "quesScore");
            return (Criteria) this;
        }

        public Criteria andQuesScoreNotIn(List<Integer> values) {
            addCriterion("ques_score not in", values, "quesScore");
            return (Criteria) this;
        }

        public Criteria andQuesScoreBetween(Integer value1, Integer value2) {
            addCriterion("ques_score between", value1, value2, "quesScore");
            return (Criteria) this;
        }

        public Criteria andQuesScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("ques_score not between", value1, value2, "quesScore");
            return (Criteria) this;
        }

        public Criteria andIsRequiredIsNull() {
            addCriterion("is_required is null");
            return (Criteria) this;
        }

        public Criteria andIsRequiredIsNotNull() {
            addCriterion("is_required is not null");
            return (Criteria) this;
        }

        public Criteria andIsRequiredEqualTo(Integer value) {
            addCriterion("is_required =", value, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredNotEqualTo(Integer value) {
            addCriterion("is_required <>", value, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredGreaterThan(Integer value) {
            addCriterion("is_required >", value, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_required >=", value, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredLessThan(Integer value) {
            addCriterion("is_required <", value, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredLessThanOrEqualTo(Integer value) {
            addCriterion("is_required <=", value, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredIn(List<Integer> values) {
            addCriterion("is_required in", values, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredNotIn(List<Integer> values) {
            addCriterion("is_required not in", values, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredBetween(Integer value1, Integer value2) {
            addCriterion("is_required between", value1, value2, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredNotBetween(Integer value1, Integer value2) {
            addCriterion("is_required not between", value1, value2, "isRequired");
            return (Criteria) this;
        }

        public Criteria andOrderByIdIsNull() {
            addCriterion("order_by_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderByIdIsNotNull() {
            addCriterion("order_by_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderByIdEqualTo(Integer value) {
            addCriterion("order_by_id =", value, "orderById");
            return (Criteria) this;
        }

        public Criteria andOrderByIdNotEqualTo(Integer value) {
            addCriterion("order_by_id <>", value, "orderById");
            return (Criteria) this;
        }

        public Criteria andOrderByIdGreaterThan(Integer value) {
            addCriterion("order_by_id >", value, "orderById");
            return (Criteria) this;
        }

        public Criteria andOrderByIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_by_id >=", value, "orderById");
            return (Criteria) this;
        }

        public Criteria andOrderByIdLessThan(Integer value) {
            addCriterion("order_by_id <", value, "orderById");
            return (Criteria) this;
        }

        public Criteria andOrderByIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_by_id <=", value, "orderById");
            return (Criteria) this;
        }

        public Criteria andOrderByIdIn(List<Integer> values) {
            addCriterion("order_by_id in", values, "orderById");
            return (Criteria) this;
        }

        public Criteria andOrderByIdNotIn(List<Integer> values) {
            addCriterion("order_by_id not in", values, "orderById");
            return (Criteria) this;
        }

        public Criteria andOrderByIdBetween(Integer value1, Integer value2) {
            addCriterion("order_by_id between", value1, value2, "orderById");
            return (Criteria) this;
        }

        public Criteria andOrderByIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_by_id not between", value1, value2, "orderById");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Boolean value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Boolean value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Boolean value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Boolean value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Boolean> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Boolean> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_an_ques
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_an_ques
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private boolean orListValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        public Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }

        public Criterion(List<Criterion> listCriterion) {
            super();
            this.value = listCriterion;
            this.orListValue = true;
        }

        public boolean isOrListValue() {
            return orListValue;
        }
    }
}