package com.crm.domain.ho;

import java.io.Serializable;
import java.util.Date;

public class LoginSource implements Serializable {
    /** 主键 */
    private Long id;

    /** 登录code */
    private String identity;

    /** 用户Id */
    private Long userId;

    /** E:M:O */
    private String type;

    /** 来源渠道（pp助手，应用宝） */
    private String channel;

    /** 1 : hr; 2 : hh; 3: admin; 4: agent */
    private Integer userType;

    /** 客户端类型（1PC，2安卓，3IOS,其他） */
    private Integer clientType;

    /** 操作系统：win7，ios10 */
    private String systemVersion;

    /** 设备型号 */
    private String mobileModel;

    /** 客户端版本：hr2.1,hr2.2/pc(浏览器版本号) */
    private String clientVersion;

    /** 创建时间 */
    private Date createTime;

    /** IP */
    private Long ip;

    /** mac 地址 */
    private String mac;

    /** 网络类型 */
    private String subtype;

    /** 省份 */
    private String province;

    /** 城市 */
    private String city;

    /** 国家 */
    private String country;

    /** userAgent */
    private String useragent;

    /** 唯一标识 */
    private String uniqueToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_login_source
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.id
     *
     * @return the value of tb_login_source.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.id
     *
     * @param id the value for tb_login_source.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.identity
     *
     * @return the value of tb_login_source.identity
     *
     * @mbggenerated
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.identity
     *
     * @param identity the value for tb_login_source.identity
     *
     * @mbggenerated
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.user_id
     *
     * @return the value of tb_login_source.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.user_id
     *
     * @param userId the value for tb_login_source.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.type
     *
     * @return the value of tb_login_source.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.type
     *
     * @param type the value for tb_login_source.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.channel
     *
     * @return the value of tb_login_source.channel
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.channel
     *
     * @param channel the value for tb_login_source.channel
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.user_type
     *
     * @return the value of tb_login_source.user_type
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.user_type
     *
     * @param userType the value for tb_login_source.user_type
     *
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.client_type
     *
     * @return the value of tb_login_source.client_type
     *
     * @mbggenerated
     */
    public Integer getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.client_type
     *
     * @param clientType the value for tb_login_source.client_type
     *
     * @mbggenerated
     */
    public void setClientType(Integer clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.system_version
     *
     * @return the value of tb_login_source.system_version
     *
     * @mbggenerated
     */
    public String getSystemVersion() {
        return systemVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.system_version
     *
     * @param systemVersion the value for tb_login_source.system_version
     *
     * @mbggenerated
     */
    public void setSystemVersion(String systemVersion) {
        this.systemVersion = systemVersion == null ? null : systemVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.mobile_model
     *
     * @return the value of tb_login_source.mobile_model
     *
     * @mbggenerated
     */
    public String getMobileModel() {
        return mobileModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.mobile_model
     *
     * @param mobileModel the value for tb_login_source.mobile_model
     *
     * @mbggenerated
     */
    public void setMobileModel(String mobileModel) {
        this.mobileModel = mobileModel == null ? null : mobileModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.client_version
     *
     * @return the value of tb_login_source.client_version
     *
     * @mbggenerated
     */
    public String getClientVersion() {
        return clientVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.client_version
     *
     * @param clientVersion the value for tb_login_source.client_version
     *
     * @mbggenerated
     */
    public void setClientVersion(String clientVersion) {
        this.clientVersion = clientVersion == null ? null : clientVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.create_time
     *
     * @return the value of tb_login_source.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.create_time
     *
     * @param createTime the value for tb_login_source.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.ip
     *
     * @return the value of tb_login_source.ip
     *
     * @mbggenerated
     */
    public Long getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.ip
     *
     * @param ip the value for tb_login_source.ip
     *
     * @mbggenerated
     */
    public void setIp(Long ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.mac
     *
     * @return the value of tb_login_source.mac
     *
     * @mbggenerated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.mac
     *
     * @param mac the value for tb_login_source.mac
     *
     * @mbggenerated
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.subtype
     *
     * @return the value of tb_login_source.subtype
     *
     * @mbggenerated
     */
    public String getSubtype() {
        return subtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.subtype
     *
     * @param subtype the value for tb_login_source.subtype
     *
     * @mbggenerated
     */
    public void setSubtype(String subtype) {
        this.subtype = subtype == null ? null : subtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.province
     *
     * @return the value of tb_login_source.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.province
     *
     * @param province the value for tb_login_source.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.city
     *
     * @return the value of tb_login_source.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.city
     *
     * @param city the value for tb_login_source.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.country
     *
     * @return the value of tb_login_source.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.country
     *
     * @param country the value for tb_login_source.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.useragent
     *
     * @return the value of tb_login_source.useragent
     *
     * @mbggenerated
     */
    public String getUseragent() {
        return useragent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.useragent
     *
     * @param useragent the value for tb_login_source.useragent
     *
     * @mbggenerated
     */
    public void setUseragent(String useragent) {
        this.useragent = useragent == null ? null : useragent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_source.unique_token
     *
     * @return the value of tb_login_source.unique_token
     *
     * @mbggenerated
     */
    public String getUniqueToken() {
        return uniqueToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_source.unique_token
     *
     * @param uniqueToken the value for tb_login_source.unique_token
     *
     * @mbggenerated
     */
    public void setUniqueToken(String uniqueToken) {
        this.uniqueToken = uniqueToken == null ? null : uniqueToken.trim();
    }
}