package com.crm.domain.backend.survey;

import java.io.Serializable;
import java.util.Date;

public class QuesSurvey implements Serializable {
    private Long id;

    /** 问卷ID */
    private String quesSurveyId;

    /** 问卷名称 */
    private String quesSurveyName;

    /** 问卷logo URL */
    private String quesSurveyLogoUrl;

    /** 问卷标题 */
    private String quesSurveyTitle;

    /** 问卷说明 */
    private String quesSurveyRemarks;

    /** 是否删除 */
    private Integer isDelete;

    private Date createTime;

    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_survey.id
     *
     * @return the value of t_an_ques_survey.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_survey.id
     *
     * @param id the value for t_an_ques_survey.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_survey.ques_survey_id
     *
     * @return the value of t_an_ques_survey.ques_survey_id
     *
     * @mbggenerated
     */
    public String getQuesSurveyId() {
        return quesSurveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_survey.ques_survey_id
     *
     * @param quesSurveyId the value for t_an_ques_survey.ques_survey_id
     *
     * @mbggenerated
     */
    public void setQuesSurveyId(String quesSurveyId) {
        this.quesSurveyId = quesSurveyId == null ? null : quesSurveyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_survey.ques_survey_name
     *
     * @return the value of t_an_ques_survey.ques_survey_name
     *
     * @mbggenerated
     */
    public String getQuesSurveyName() {
        return quesSurveyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_survey.ques_survey_name
     *
     * @param quesSurveyName the value for t_an_ques_survey.ques_survey_name
     *
     * @mbggenerated
     */
    public void setQuesSurveyName(String quesSurveyName) {
        this.quesSurveyName = quesSurveyName == null ? null : quesSurveyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_survey.ques_survey_logo_url
     *
     * @return the value of t_an_ques_survey.ques_survey_logo_url
     *
     * @mbggenerated
     */
    public String getQuesSurveyLogoUrl() {
        return quesSurveyLogoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_survey.ques_survey_logo_url
     *
     * @param quesSurveyLogoUrl the value for t_an_ques_survey.ques_survey_logo_url
     *
     * @mbggenerated
     */
    public void setQuesSurveyLogoUrl(String quesSurveyLogoUrl) {
        this.quesSurveyLogoUrl = quesSurveyLogoUrl == null ? null : quesSurveyLogoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_survey.ques_survey_title
     *
     * @return the value of t_an_ques_survey.ques_survey_title
     *
     * @mbggenerated
     */
    public String getQuesSurveyTitle() {
        return quesSurveyTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_survey.ques_survey_title
     *
     * @param quesSurveyTitle the value for t_an_ques_survey.ques_survey_title
     *
     * @mbggenerated
     */
    public void setQuesSurveyTitle(String quesSurveyTitle) {
        this.quesSurveyTitle = quesSurveyTitle == null ? null : quesSurveyTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_survey.ques_survey_remarks
     *
     * @return the value of t_an_ques_survey.ques_survey_remarks
     *
     * @mbggenerated
     */
    public String getQuesSurveyRemarks() {
        return quesSurveyRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_survey.ques_survey_remarks
     *
     * @param quesSurveyRemarks the value for t_an_ques_survey.ques_survey_remarks
     *
     * @mbggenerated
     */
    public void setQuesSurveyRemarks(String quesSurveyRemarks) {
        this.quesSurveyRemarks = quesSurveyRemarks == null ? null : quesSurveyRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_survey.is_delete
     *
     * @return the value of t_an_ques_survey.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_survey.is_delete
     *
     * @param isDelete the value for t_an_ques_survey.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_survey.create_time
     *
     * @return the value of t_an_ques_survey.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_survey.create_time
     *
     * @param createTime the value for t_an_ques_survey.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_survey.update_time
     *
     * @return the value of t_an_ques_survey.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_survey.update_time
     *
     * @param updateTime the value for t_an_ques_survey.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}