package com.crm.domain.backend.survey;

import com.crm.util.mybatis.plugin.Limit;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QuesSurveyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    private Limit limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public QuesSurveyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Limit limit) {
        this.limit = limit;
    }

    public Limit getLimit() {
        return this.limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(Criterion criterion) {
            if (criterion == null) {
                throw new RuntimeException("Value for criterion cannot be null");
            }
            criteria.add(criterion);
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuesSurveyIdIsNull() {
            addCriterion("ques_survey_id is null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdIsNotNull() {
            addCriterion("ques_survey_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdEqualTo(Long value) {
            addCriterion("ques_survey_id =", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdNotEqualTo(Long value) {
            addCriterion("ques_survey_id <>", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdGreaterThan(Long value) {
            addCriterion("ques_survey_id >", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ques_survey_id >=", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdLessThan(Long value) {
            addCriterion("ques_survey_id <", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdLessThanOrEqualTo(Long value) {
            addCriterion("ques_survey_id <=", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdIn(List<Long> values) {
            addCriterion("ques_survey_id in", values, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdNotIn(List<Long> values) {
            addCriterion("ques_survey_id not in", values, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdBetween(Long value1, Long value2) {
            addCriterion("ques_survey_id between", value1, value2, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdNotBetween(Long value1, Long value2) {
            addCriterion("ques_survey_id not between", value1, value2, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameIsNull() {
            addCriterion("ques_survey_name is null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameIsNotNull() {
            addCriterion("ques_survey_name is not null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameEqualTo(String value) {
            addCriterion("ques_survey_name =", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameNotEqualTo(String value) {
            addCriterion("ques_survey_name <>", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameGreaterThan(String value) {
            addCriterion("ques_survey_name >", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameGreaterThanOrEqualTo(String value) {
            addCriterion("ques_survey_name >=", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameLessThan(String value) {
            addCriterion("ques_survey_name <", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameLessThanOrEqualTo(String value) {
            addCriterion("ques_survey_name <=", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameLike(String value) {
            addCriterion("ques_survey_name like", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameNotLike(String value) {
            addCriterion("ques_survey_name not like", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameIn(List<String> values) {
            addCriterion("ques_survey_name in", values, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameNotIn(List<String> values) {
            addCriterion("ques_survey_name not in", values, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameBetween(String value1, String value2) {
            addCriterion("ques_survey_name between", value1, value2, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameNotBetween(String value1, String value2) {
            addCriterion("ques_survey_name not between", value1, value2, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlIsNull() {
            addCriterion("ques_survey_logo_url is null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlIsNotNull() {
            addCriterion("ques_survey_logo_url is not null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlEqualTo(String value) {
            addCriterion("ques_survey_logo_url =", value, "quesSurveyLogoUrl");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlNotEqualTo(String value) {
            addCriterion("ques_survey_logo_url <>", value, "quesSurveyLogoUrl");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlGreaterThan(String value) {
            addCriterion("ques_survey_logo_url >", value, "quesSurveyLogoUrl");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("ques_survey_logo_url >=", value, "quesSurveyLogoUrl");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlLessThan(String value) {
            addCriterion("ques_survey_logo_url <", value, "quesSurveyLogoUrl");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlLessThanOrEqualTo(String value) {
            addCriterion("ques_survey_logo_url <=", value, "quesSurveyLogoUrl");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlLike(String value) {
            addCriterion("ques_survey_logo_url like", value, "quesSurveyLogoUrl");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlNotLike(String value) {
            addCriterion("ques_survey_logo_url not like", value, "quesSurveyLogoUrl");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlIn(List<String> values) {
            addCriterion("ques_survey_logo_url in", values, "quesSurveyLogoUrl");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlNotIn(List<String> values) {
            addCriterion("ques_survey_logo_url not in", values, "quesSurveyLogoUrl");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlBetween(String value1, String value2) {
            addCriterion("ques_survey_logo_url between", value1, value2, "quesSurveyLogoUrl");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyLogoUrlNotBetween(String value1, String value2) {
            addCriterion("ques_survey_logo_url not between", value1, value2, "quesSurveyLogoUrl");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleIsNull() {
            addCriterion("ques_survey_title is null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleIsNotNull() {
            addCriterion("ques_survey_title is not null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleEqualTo(String value) {
            addCriterion("ques_survey_title =", value, "quesSurveyTitle");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleNotEqualTo(String value) {
            addCriterion("ques_survey_title <>", value, "quesSurveyTitle");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleGreaterThan(String value) {
            addCriterion("ques_survey_title >", value, "quesSurveyTitle");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleGreaterThanOrEqualTo(String value) {
            addCriterion("ques_survey_title >=", value, "quesSurveyTitle");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleLessThan(String value) {
            addCriterion("ques_survey_title <", value, "quesSurveyTitle");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleLessThanOrEqualTo(String value) {
            addCriterion("ques_survey_title <=", value, "quesSurveyTitle");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleLike(String value) {
            addCriterion("ques_survey_title like", value, "quesSurveyTitle");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleNotLike(String value) {
            addCriterion("ques_survey_title not like", value, "quesSurveyTitle");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleIn(List<String> values) {
            addCriterion("ques_survey_title in", values, "quesSurveyTitle");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleNotIn(List<String> values) {
            addCriterion("ques_survey_title not in", values, "quesSurveyTitle");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleBetween(String value1, String value2) {
            addCriterion("ques_survey_title between", value1, value2, "quesSurveyTitle");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyTitleNotBetween(String value1, String value2) {
            addCriterion("ques_survey_title not between", value1, value2, "quesSurveyTitle");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksIsNull() {
            addCriterion("ques_survey_remarks is null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksIsNotNull() {
            addCriterion("ques_survey_remarks is not null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksEqualTo(String value) {
            addCriterion("ques_survey_remarks =", value, "quesSurveyRemarks");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksNotEqualTo(String value) {
            addCriterion("ques_survey_remarks <>", value, "quesSurveyRemarks");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksGreaterThan(String value) {
            addCriterion("ques_survey_remarks >", value, "quesSurveyRemarks");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("ques_survey_remarks >=", value, "quesSurveyRemarks");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksLessThan(String value) {
            addCriterion("ques_survey_remarks <", value, "quesSurveyRemarks");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksLessThanOrEqualTo(String value) {
            addCriterion("ques_survey_remarks <=", value, "quesSurveyRemarks");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksLike(String value) {
            addCriterion("ques_survey_remarks like", value, "quesSurveyRemarks");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksNotLike(String value) {
            addCriterion("ques_survey_remarks not like", value, "quesSurveyRemarks");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksIn(List<String> values) {
            addCriterion("ques_survey_remarks in", values, "quesSurveyRemarks");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksNotIn(List<String> values) {
            addCriterion("ques_survey_remarks not in", values, "quesSurveyRemarks");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksBetween(String value1, String value2) {
            addCriterion("ques_survey_remarks between", value1, value2, "quesSurveyRemarks");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyRemarksNotBetween(String value1, String value2) {
            addCriterion("ques_survey_remarks not between", value1, value2, "quesSurveyRemarks");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Boolean value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Boolean value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Boolean value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Boolean value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Boolean> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Boolean> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private boolean orListValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        public Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }

        public Criterion(List<Criterion> listCriterion) {
            super();
            this.value = listCriterion;
            this.orListValue = true;
        }

        public boolean isOrListValue() {
            return orListValue;
        }
    }
}