package com.crm.domain.backend.survey;

import java.io.Serializable;
import java.util.Date;

public class QuesType implements Serializable {
    /** 题目大类ID */
    private Long quesTypeId;

    /** 题目大类名称 */
    private String quesTypeName;

    private String quesTypeEnglishName;

    private String quesTypeRemarks;

    /** 所属问卷ID */
    private Long quesSurveyId;

    /** 排序 */
    private Integer orderById;

    /** 是否背景调查 */
    private Integer isBackgroundSurvey;

    /** 是否删除 */
    private Boolean isDelete;

    private Date createTime;

    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.ques_type_id
     *
     * @return the value of t_an_ques_type.ques_type_id
     *
     * @mbggenerated
     */
    public Long getQuesTypeId() {
        return quesTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.ques_type_id
     *
     * @param quesTypeId the value for t_an_ques_type.ques_type_id
     *
     * @mbggenerated
     */
    public void setQuesTypeId(Long quesTypeId) {
        this.quesTypeId = quesTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.ques_type_name
     *
     * @return the value of t_an_ques_type.ques_type_name
     *
     * @mbggenerated
     */
    public String getQuesTypeName() {
        return quesTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.ques_type_name
     *
     * @param quesTypeName the value for t_an_ques_type.ques_type_name
     *
     * @mbggenerated
     */
    public void setQuesTypeName(String quesTypeName) {
        this.quesTypeName = quesTypeName == null ? null : quesTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.ques_type_english_name
     *
     * @return the value of t_an_ques_type.ques_type_english_name
     *
     * @mbggenerated
     */
    public String getQuesTypeEnglishName() {
        return quesTypeEnglishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.ques_type_english_name
     *
     * @param quesTypeEnglishName the value for t_an_ques_type.ques_type_english_name
     *
     * @mbggenerated
     */
    public void setQuesTypeEnglishName(String quesTypeEnglishName) {
        this.quesTypeEnglishName = quesTypeEnglishName == null ? null : quesTypeEnglishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.ques_type_remarks
     *
     * @return the value of t_an_ques_type.ques_type_remarks
     *
     * @mbggenerated
     */
    public String getQuesTypeRemarks() {
        return quesTypeRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.ques_type_remarks
     *
     * @param quesTypeRemarks the value for t_an_ques_type.ques_type_remarks
     *
     * @mbggenerated
     */
    public void setQuesTypeRemarks(String quesTypeRemarks) {
        this.quesTypeRemarks = quesTypeRemarks == null ? null : quesTypeRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.ques_survey_id
     *
     * @return the value of t_an_ques_type.ques_survey_id
     *
     * @mbggenerated
     */
    public Long getQuesSurveyId() {
        return quesSurveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.ques_survey_id
     *
     * @param quesSurveyId the value for t_an_ques_type.ques_survey_id
     *
     * @mbggenerated
     */
    public void setQuesSurveyId(Long quesSurveyId) {
        this.quesSurveyId = quesSurveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.order_by_id
     *
     * @return the value of t_an_ques_type.order_by_id
     *
     * @mbggenerated
     */
    public Integer getOrderById() {
        return orderById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.order_by_id
     *
     * @param orderById the value for t_an_ques_type.order_by_id
     *
     * @mbggenerated
     */
    public void setOrderById(Integer orderById) {
        this.orderById = orderById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.is_background_survey
     *
     * @return the value of t_an_ques_type.is_background_survey
     *
     * @mbggenerated
     */
    public Integer getIsBackgroundSurvey() {
        return isBackgroundSurvey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.is_background_survey
     *
     * @param isBackgroundSurvey the value for t_an_ques_type.is_background_survey
     *
     * @mbggenerated
     */
    public void setIsBackgroundSurvey(Integer isBackgroundSurvey) {
        this.isBackgroundSurvey = isBackgroundSurvey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.is_delete
     *
     * @return the value of t_an_ques_type.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.is_delete
     *
     * @param isDelete the value for t_an_ques_type.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.create_time
     *
     * @return the value of t_an_ques_type.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.create_time
     *
     * @param createTime the value for t_an_ques_type.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.update_time
     *
     * @return the value of t_an_ques_type.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.update_time
     *
     * @param updateTime the value for t_an_ques_type.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}