package com.crm.domain.backend.survey;

import java.io.Serializable;
import java.util.Date;

public class QuesType implements Serializable {
    private Long id;

    /** 题目大类ID */
    private String quesTypeId;

    /** 题目大类名称 */
    private String quesTypeName;

    /** 所属问卷ID */
    private String quesSurveyId;

    /** 排序 */
    private Integer orderById;

    /** 是否删除 */
    private Integer isDelete;

    private Date createTime;

    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.id
     *
     * @return the value of t_an_ques_type.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.id
     *
     * @param id the value for t_an_ques_type.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.ques_type_id
     *
     * @return the value of t_an_ques_type.ques_type_id
     *
     * @mbggenerated
     */
    public String getQuesTypeId() {
        return quesTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.ques_type_id
     *
     * @param quesTypeId the value for t_an_ques_type.ques_type_id
     *
     * @mbggenerated
     */
    public void setQuesTypeId(String quesTypeId) {
        this.quesTypeId = quesTypeId == null ? null : quesTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.ques_type_name
     *
     * @return the value of t_an_ques_type.ques_type_name
     *
     * @mbggenerated
     */
    public String getQuesTypeName() {
        return quesTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.ques_type_name
     *
     * @param quesTypeName the value for t_an_ques_type.ques_type_name
     *
     * @mbggenerated
     */
    public void setQuesTypeName(String quesTypeName) {
        this.quesTypeName = quesTypeName == null ? null : quesTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.ques_survey_id
     *
     * @return the value of t_an_ques_type.ques_survey_id
     *
     * @mbggenerated
     */
    public String getQuesSurveyId() {
        return quesSurveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.ques_survey_id
     *
     * @param quesSurveyId the value for t_an_ques_type.ques_survey_id
     *
     * @mbggenerated
     */
    public void setQuesSurveyId(String quesSurveyId) {
        this.quesSurveyId = quesSurveyId == null ? null : quesSurveyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.order_by_id
     *
     * @return the value of t_an_ques_type.order_by_id
     *
     * @mbggenerated
     */
    public Integer getOrderById() {
        return orderById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.order_by_id
     *
     * @param orderById the value for t_an_ques_type.order_by_id
     *
     * @mbggenerated
     */
    public void setOrderById(Integer orderById) {
        this.orderById = orderById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.is_delete
     *
     * @return the value of t_an_ques_type.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.is_delete
     *
     * @param isDelete the value for t_an_ques_type.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.create_time
     *
     * @return the value of t_an_ques_type.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.create_time
     *
     * @param createTime the value for t_an_ques_type.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_an_ques_type.update_time
     *
     * @return the value of t_an_ques_type.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_an_ques_type.update_time
     *
     * @param updateTime the value for t_an_ques_type.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}