package com.crm.domain.backend.survey;

import com.crm.util.mybatis.plugin.Limit;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QuesSurveyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    private Limit limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public QuesSurveyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Limit limit) {
        this.limit = limit;
    }

    public Limit getLimit() {
        return this.limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(Criterion criterion) {
            if (criterion == null) {
                throw new RuntimeException("Value for criterion cannot be null");
            }
            criteria.add(criterion);
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idIsNull() {
            addCriterion("ques_survey_id is null");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idIsNotNull() {
            addCriterion("ques_survey_id is not null");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idEqualTo(String value) {
            addCriterion("ques_survey_id =", value, "ques_survey_id");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idNotEqualTo(String value) {
            addCriterion("ques_survey_id <>", value, "ques_survey_id");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idGreaterThan(String value) {
            addCriterion("ques_survey_id >", value, "ques_survey_id");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idGreaterThanOrEqualTo(String value) {
            addCriterion("ques_survey_id >=", value, "ques_survey_id");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idLessThan(String value) {
            addCriterion("ques_survey_id <", value, "ques_survey_id");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idLessThanOrEqualTo(String value) {
            addCriterion("ques_survey_id <=", value, "ques_survey_id");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idLike(String value) {
            addCriterion("ques_survey_id like", value, "ques_survey_id");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idNotLike(String value) {
            addCriterion("ques_survey_id not like", value, "ques_survey_id");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idIn(List<String> values) {
            addCriterion("ques_survey_id in", values, "ques_survey_id");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idNotIn(List<String> values) {
            addCriterion("ques_survey_id not in", values, "ques_survey_id");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idBetween(String value1, String value2) {
            addCriterion("ques_survey_id between", value1, value2, "ques_survey_id");
            return (Criteria) this;
        }

        public Criteria andQues_survey_idNotBetween(String value1, String value2) {
            addCriterion("ques_survey_id not between", value1, value2, "ques_survey_id");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameIsNull() {
            addCriterion("ques_survey_name is null");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameIsNotNull() {
            addCriterion("ques_survey_name is not null");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameEqualTo(String value) {
            addCriterion("ques_survey_name =", value, "ques_survey_name");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameNotEqualTo(String value) {
            addCriterion("ques_survey_name <>", value, "ques_survey_name");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameGreaterThan(String value) {
            addCriterion("ques_survey_name >", value, "ques_survey_name");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameGreaterThanOrEqualTo(String value) {
            addCriterion("ques_survey_name >=", value, "ques_survey_name");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameLessThan(String value) {
            addCriterion("ques_survey_name <", value, "ques_survey_name");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameLessThanOrEqualTo(String value) {
            addCriterion("ques_survey_name <=", value, "ques_survey_name");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameLike(String value) {
            addCriterion("ques_survey_name like", value, "ques_survey_name");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameNotLike(String value) {
            addCriterion("ques_survey_name not like", value, "ques_survey_name");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameIn(List<String> values) {
            addCriterion("ques_survey_name in", values, "ques_survey_name");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameNotIn(List<String> values) {
            addCriterion("ques_survey_name not in", values, "ques_survey_name");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameBetween(String value1, String value2) {
            addCriterion("ques_survey_name between", value1, value2, "ques_survey_name");
            return (Criteria) this;
        }

        public Criteria andQues_survey_nameNotBetween(String value1, String value2) {
            addCriterion("ques_survey_name not between", value1, value2, "ques_survey_name");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlIsNull() {
            addCriterion("ques_survey_logo_url is null");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlIsNotNull() {
            addCriterion("ques_survey_logo_url is not null");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlEqualTo(String value) {
            addCriterion("ques_survey_logo_url =", value, "ques_survey_logo_url");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlNotEqualTo(String value) {
            addCriterion("ques_survey_logo_url <>", value, "ques_survey_logo_url");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlGreaterThan(String value) {
            addCriterion("ques_survey_logo_url >", value, "ques_survey_logo_url");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlGreaterThanOrEqualTo(String value) {
            addCriterion("ques_survey_logo_url >=", value, "ques_survey_logo_url");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlLessThan(String value) {
            addCriterion("ques_survey_logo_url <", value, "ques_survey_logo_url");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlLessThanOrEqualTo(String value) {
            addCriterion("ques_survey_logo_url <=", value, "ques_survey_logo_url");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlLike(String value) {
            addCriterion("ques_survey_logo_url like", value, "ques_survey_logo_url");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlNotLike(String value) {
            addCriterion("ques_survey_logo_url not like", value, "ques_survey_logo_url");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlIn(List<String> values) {
            addCriterion("ques_survey_logo_url in", values, "ques_survey_logo_url");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlNotIn(List<String> values) {
            addCriterion("ques_survey_logo_url not in", values, "ques_survey_logo_url");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlBetween(String value1, String value2) {
            addCriterion("ques_survey_logo_url between", value1, value2, "ques_survey_logo_url");
            return (Criteria) this;
        }

        public Criteria andQues_survey_logo_urlNotBetween(String value1, String value2) {
            addCriterion("ques_survey_logo_url not between", value1, value2, "ques_survey_logo_url");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleIsNull() {
            addCriterion("ques_survey_title is null");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleIsNotNull() {
            addCriterion("ques_survey_title is not null");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleEqualTo(String value) {
            addCriterion("ques_survey_title =", value, "ques_survey_title");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleNotEqualTo(String value) {
            addCriterion("ques_survey_title <>", value, "ques_survey_title");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleGreaterThan(String value) {
            addCriterion("ques_survey_title >", value, "ques_survey_title");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleGreaterThanOrEqualTo(String value) {
            addCriterion("ques_survey_title >=", value, "ques_survey_title");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleLessThan(String value) {
            addCriterion("ques_survey_title <", value, "ques_survey_title");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleLessThanOrEqualTo(String value) {
            addCriterion("ques_survey_title <=", value, "ques_survey_title");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleLike(String value) {
            addCriterion("ques_survey_title like", value, "ques_survey_title");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleNotLike(String value) {
            addCriterion("ques_survey_title not like", value, "ques_survey_title");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleIn(List<String> values) {
            addCriterion("ques_survey_title in", values, "ques_survey_title");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleNotIn(List<String> values) {
            addCriterion("ques_survey_title not in", values, "ques_survey_title");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleBetween(String value1, String value2) {
            addCriterion("ques_survey_title between", value1, value2, "ques_survey_title");
            return (Criteria) this;
        }

        public Criteria andQues_survey_titleNotBetween(String value1, String value2) {
            addCriterion("ques_survey_title not between", value1, value2, "ques_survey_title");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksIsNull() {
            addCriterion("ques_survey_remarks is null");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksIsNotNull() {
            addCriterion("ques_survey_remarks is not null");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksEqualTo(String value) {
            addCriterion("ques_survey_remarks =", value, "ques_survey_remarks");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksNotEqualTo(String value) {
            addCriterion("ques_survey_remarks <>", value, "ques_survey_remarks");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksGreaterThan(String value) {
            addCriterion("ques_survey_remarks >", value, "ques_survey_remarks");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksGreaterThanOrEqualTo(String value) {
            addCriterion("ques_survey_remarks >=", value, "ques_survey_remarks");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksLessThan(String value) {
            addCriterion("ques_survey_remarks <", value, "ques_survey_remarks");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksLessThanOrEqualTo(String value) {
            addCriterion("ques_survey_remarks <=", value, "ques_survey_remarks");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksLike(String value) {
            addCriterion("ques_survey_remarks like", value, "ques_survey_remarks");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksNotLike(String value) {
            addCriterion("ques_survey_remarks not like", value, "ques_survey_remarks");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksIn(List<String> values) {
            addCriterion("ques_survey_remarks in", values, "ques_survey_remarks");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksNotIn(List<String> values) {
            addCriterion("ques_survey_remarks not in", values, "ques_survey_remarks");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksBetween(String value1, String value2) {
            addCriterion("ques_survey_remarks between", value1, value2, "ques_survey_remarks");
            return (Criteria) this;
        }

        public Criteria andQues_survey_remarksNotBetween(String value1, String value2) {
            addCriterion("ques_survey_remarks not between", value1, value2, "ques_survey_remarks");
            return (Criteria) this;
        }

        public Criteria andIs_deleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIs_deleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIs_deleteEqualTo(Integer value) {
            addCriterion("is_delete =", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteNotEqualTo(Integer value) {
            addCriterion("is_delete <>", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteGreaterThan(Integer value) {
            addCriterion("is_delete >", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_delete >=", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteLessThan(Integer value) {
            addCriterion("is_delete <", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteLessThanOrEqualTo(Integer value) {
            addCriterion("is_delete <=", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteIn(List<Integer> values) {
            addCriterion("is_delete in", values, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteNotIn(List<Integer> values) {
            addCriterion("is_delete not in", values, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteBetween(Integer value1, Integer value2) {
            addCriterion("is_delete between", value1, value2, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteNotBetween(Integer value1, Integer value2) {
            addCriterion("is_delete not between", value1, value2, "is_delete");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeEqualTo(Date value) {
            addCriterion("update_time =", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThan(Date value) {
            addCriterion("update_time >", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThan(Date value) {
            addCriterion("update_time <", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIn(List<Date> values) {
            addCriterion("update_time in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "update_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_an_ques_survey
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private boolean orListValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        public Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }

        public Criterion(List<Criterion> listCriterion) {
            super();
            this.value = listCriterion;
            this.orListValue = true;
        }

        public boolean isOrListValue() {
            return orListValue;
        }
    }
}