package com.crm.domain.backend.survey;

import com.crm.util.mybatis.plugin.Limit;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QuesSurveyAnsweredDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    private Limit limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    public QuesSurveyAnsweredDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Limit limit) {
        this.limit = limit;
    }

    public Limit getLimit() {
        return this.limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(Criterion criterion) {
            if (criterion == null) {
                throw new RuntimeException("Value for criterion cannot be null");
            }
            criteria.add(criterion);
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuesSurveyAnsweredIdIsNull() {
            addCriterion("ques_survey_answered_id is null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyAnsweredIdIsNotNull() {
            addCriterion("ques_survey_answered_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyAnsweredIdEqualTo(Long value) {
            addCriterion("ques_survey_answered_id =", value, "quesSurveyAnsweredId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyAnsweredIdNotEqualTo(Long value) {
            addCriterion("ques_survey_answered_id <>", value, "quesSurveyAnsweredId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyAnsweredIdGreaterThan(Long value) {
            addCriterion("ques_survey_answered_id >", value, "quesSurveyAnsweredId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyAnsweredIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ques_survey_answered_id >=", value, "quesSurveyAnsweredId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyAnsweredIdLessThan(Long value) {
            addCriterion("ques_survey_answered_id <", value, "quesSurveyAnsweredId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyAnsweredIdLessThanOrEqualTo(Long value) {
            addCriterion("ques_survey_answered_id <=", value, "quesSurveyAnsweredId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyAnsweredIdIn(List<Long> values) {
            addCriterion("ques_survey_answered_id in", values, "quesSurveyAnsweredId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyAnsweredIdNotIn(List<Long> values) {
            addCriterion("ques_survey_answered_id not in", values, "quesSurveyAnsweredId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyAnsweredIdBetween(Long value1, Long value2) {
            addCriterion("ques_survey_answered_id between", value1, value2, "quesSurveyAnsweredId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyAnsweredIdNotBetween(Long value1, Long value2) {
            addCriterion("ques_survey_answered_id not between", value1, value2, "quesSurveyAnsweredId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdIsNull() {
            addCriterion("ques_survey_id is null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdIsNotNull() {
            addCriterion("ques_survey_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdEqualTo(Long value) {
            addCriterion("ques_survey_id =", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdNotEqualTo(Long value) {
            addCriterion("ques_survey_id <>", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdGreaterThan(Long value) {
            addCriterion("ques_survey_id >", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ques_survey_id >=", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdLessThan(Long value) {
            addCriterion("ques_survey_id <", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdLessThanOrEqualTo(Long value) {
            addCriterion("ques_survey_id <=", value, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdIn(List<Long> values) {
            addCriterion("ques_survey_id in", values, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdNotIn(List<Long> values) {
            addCriterion("ques_survey_id not in", values, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdBetween(Long value1, Long value2) {
            addCriterion("ques_survey_id between", value1, value2, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyIdNotBetween(Long value1, Long value2) {
            addCriterion("ques_survey_id not between", value1, value2, "quesSurveyId");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameIsNull() {
            addCriterion("ques_survey_name is null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameIsNotNull() {
            addCriterion("ques_survey_name is not null");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameEqualTo(String value) {
            addCriterion("ques_survey_name =", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameNotEqualTo(String value) {
            addCriterion("ques_survey_name <>", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameGreaterThan(String value) {
            addCriterion("ques_survey_name >", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameGreaterThanOrEqualTo(String value) {
            addCriterion("ques_survey_name >=", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameLessThan(String value) {
            addCriterion("ques_survey_name <", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameLessThanOrEqualTo(String value) {
            addCriterion("ques_survey_name <=", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameLike(String value) {
            addCriterion("ques_survey_name like", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameNotLike(String value) {
            addCriterion("ques_survey_name not like", value, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameIn(List<String> values) {
            addCriterion("ques_survey_name in", values, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameNotIn(List<String> values) {
            addCriterion("ques_survey_name not in", values, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameBetween(String value1, String value2) {
            addCriterion("ques_survey_name between", value1, value2, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesSurveyNameNotBetween(String value1, String value2) {
            addCriterion("ques_survey_name not between", value1, value2, "quesSurveyName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdIsNull() {
            addCriterion("ques_type_id is null");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdIsNotNull() {
            addCriterion("ques_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdEqualTo(Long value) {
            addCriterion("ques_type_id =", value, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdNotEqualTo(Long value) {
            addCriterion("ques_type_id <>", value, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdGreaterThan(Long value) {
            addCriterion("ques_type_id >", value, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ques_type_id >=", value, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdLessThan(Long value) {
            addCriterion("ques_type_id <", value, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdLessThanOrEqualTo(Long value) {
            addCriterion("ques_type_id <=", value, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdIn(List<Long> values) {
            addCriterion("ques_type_id in", values, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdNotIn(List<Long> values) {
            addCriterion("ques_type_id not in", values, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdBetween(Long value1, Long value2) {
            addCriterion("ques_type_id between", value1, value2, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIdNotBetween(Long value1, Long value2) {
            addCriterion("ques_type_id not between", value1, value2, "quesTypeId");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameIsNull() {
            addCriterion("ques_type_name is null");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameIsNotNull() {
            addCriterion("ques_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameEqualTo(String value) {
            addCriterion("ques_type_name =", value, "quesTypeName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameNotEqualTo(String value) {
            addCriterion("ques_type_name <>", value, "quesTypeName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameGreaterThan(String value) {
            addCriterion("ques_type_name >", value, "quesTypeName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("ques_type_name >=", value, "quesTypeName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameLessThan(String value) {
            addCriterion("ques_type_name <", value, "quesTypeName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameLessThanOrEqualTo(String value) {
            addCriterion("ques_type_name <=", value, "quesTypeName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameLike(String value) {
            addCriterion("ques_type_name like", value, "quesTypeName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameNotLike(String value) {
            addCriterion("ques_type_name not like", value, "quesTypeName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameIn(List<String> values) {
            addCriterion("ques_type_name in", values, "quesTypeName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameNotIn(List<String> values) {
            addCriterion("ques_type_name not in", values, "quesTypeName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameBetween(String value1, String value2) {
            addCriterion("ques_type_name between", value1, value2, "quesTypeName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNameNotBetween(String value1, String value2) {
            addCriterion("ques_type_name not between", value1, value2, "quesTypeName");
            return (Criteria) this;
        }

        public Criteria andQuesIdIsNull() {
            addCriterion("ques_id is null");
            return (Criteria) this;
        }

        public Criteria andQuesIdIsNotNull() {
            addCriterion("ques_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuesIdEqualTo(Long value) {
            addCriterion("ques_id =", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdNotEqualTo(Long value) {
            addCriterion("ques_id <>", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdGreaterThan(Long value) {
            addCriterion("ques_id >", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ques_id >=", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdLessThan(Long value) {
            addCriterion("ques_id <", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdLessThanOrEqualTo(Long value) {
            addCriterion("ques_id <=", value, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdIn(List<Long> values) {
            addCriterion("ques_id in", values, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdNotIn(List<Long> values) {
            addCriterion("ques_id not in", values, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdBetween(Long value1, Long value2) {
            addCriterion("ques_id between", value1, value2, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesIdNotBetween(Long value1, Long value2) {
            addCriterion("ques_id not between", value1, value2, "quesId");
            return (Criteria) this;
        }

        public Criteria andQuesNameIsNull() {
            addCriterion("ques_name is null");
            return (Criteria) this;
        }

        public Criteria andQuesNameIsNotNull() {
            addCriterion("ques_name is not null");
            return (Criteria) this;
        }

        public Criteria andQuesNameEqualTo(String value) {
            addCriterion("ques_name =", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameNotEqualTo(String value) {
            addCriterion("ques_name <>", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameGreaterThan(String value) {
            addCriterion("ques_name >", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameGreaterThanOrEqualTo(String value) {
            addCriterion("ques_name >=", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameLessThan(String value) {
            addCriterion("ques_name <", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameLessThanOrEqualTo(String value) {
            addCriterion("ques_name <=", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameLike(String value) {
            addCriterion("ques_name like", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameNotLike(String value) {
            addCriterion("ques_name not like", value, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameIn(List<String> values) {
            addCriterion("ques_name in", values, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameNotIn(List<String> values) {
            addCriterion("ques_name not in", values, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameBetween(String value1, String value2) {
            addCriterion("ques_name between", value1, value2, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesNameNotBetween(String value1, String value2) {
            addCriterion("ques_name not between", value1, value2, "quesName");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIsNull() {
            addCriterion("ques_type is null");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIsNotNull() {
            addCriterion("ques_type is not null");
            return (Criteria) this;
        }

        public Criteria andQuesTypeEqualTo(Integer value) {
            addCriterion("ques_type =", value, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNotEqualTo(Integer value) {
            addCriterion("ques_type <>", value, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeGreaterThan(Integer value) {
            addCriterion("ques_type >", value, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ques_type >=", value, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeLessThan(Integer value) {
            addCriterion("ques_type <", value, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeLessThanOrEqualTo(Integer value) {
            addCriterion("ques_type <=", value, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeIn(List<Integer> values) {
            addCriterion("ques_type in", values, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNotIn(List<Integer> values) {
            addCriterion("ques_type not in", values, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeBetween(Integer value1, Integer value2) {
            addCriterion("ques_type between", value1, value2, "quesType");
            return (Criteria) this;
        }

        public Criteria andQuesTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("ques_type not between", value1, value2, "quesType");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIsNull() {
            addCriterion("answer_id is null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIsNotNull() {
            addCriterion("answer_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdEqualTo(Long value) {
            addCriterion("answer_id =", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotEqualTo(Long value) {
            addCriterion("answer_id <>", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThan(Long value) {
            addCriterion("answer_id >", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("answer_id >=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThan(Long value) {
            addCriterion("answer_id <", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThanOrEqualTo(Long value) {
            addCriterion("answer_id <=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIn(List<Long> values) {
            addCriterion("answer_id in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotIn(List<Long> values) {
            addCriterion("answer_id not in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdBetween(Long value1, Long value2) {
            addCriterion("answer_id between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotBetween(Long value1, Long value2) {
            addCriterion("answer_id not between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerNameIsNull() {
            addCriterion("answer_name is null");
            return (Criteria) this;
        }

        public Criteria andAnswerNameIsNotNull() {
            addCriterion("answer_name is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerNameEqualTo(String value) {
            addCriterion("answer_name =", value, "answerName");
            return (Criteria) this;
        }

        public Criteria andAnswerNameNotEqualTo(String value) {
            addCriterion("answer_name <>", value, "answerName");
            return (Criteria) this;
        }

        public Criteria andAnswerNameGreaterThan(String value) {
            addCriterion("answer_name >", value, "answerName");
            return (Criteria) this;
        }

        public Criteria andAnswerNameGreaterThanOrEqualTo(String value) {
            addCriterion("answer_name >=", value, "answerName");
            return (Criteria) this;
        }

        public Criteria andAnswerNameLessThan(String value) {
            addCriterion("answer_name <", value, "answerName");
            return (Criteria) this;
        }

        public Criteria andAnswerNameLessThanOrEqualTo(String value) {
            addCriterion("answer_name <=", value, "answerName");
            return (Criteria) this;
        }

        public Criteria andAnswerNameLike(String value) {
            addCriterion("answer_name like", value, "answerName");
            return (Criteria) this;
        }

        public Criteria andAnswerNameNotLike(String value) {
            addCriterion("answer_name not like", value, "answerName");
            return (Criteria) this;
        }

        public Criteria andAnswerNameIn(List<String> values) {
            addCriterion("answer_name in", values, "answerName");
            return (Criteria) this;
        }

        public Criteria andAnswerNameNotIn(List<String> values) {
            addCriterion("answer_name not in", values, "answerName");
            return (Criteria) this;
        }

        public Criteria andAnswerNameBetween(String value1, String value2) {
            addCriterion("answer_name between", value1, value2, "answerName");
            return (Criteria) this;
        }

        public Criteria andAnswerNameNotBetween(String value1, String value2) {
            addCriterion("answer_name not between", value1, value2, "answerName");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreIsNull() {
            addCriterion("answer_score is null");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreIsNotNull() {
            addCriterion("answer_score is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreEqualTo(String value) {
            addCriterion("answer_score =", value, "answerScore");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreNotEqualTo(String value) {
            addCriterion("answer_score <>", value, "answerScore");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreGreaterThan(String value) {
            addCriterion("answer_score >", value, "answerScore");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreGreaterThanOrEqualTo(String value) {
            addCriterion("answer_score >=", value, "answerScore");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreLessThan(String value) {
            addCriterion("answer_score <", value, "answerScore");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreLessThanOrEqualTo(String value) {
            addCriterion("answer_score <=", value, "answerScore");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreLike(String value) {
            addCriterion("answer_score like", value, "answerScore");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreNotLike(String value) {
            addCriterion("answer_score not like", value, "answerScore");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreIn(List<String> values) {
            addCriterion("answer_score in", values, "answerScore");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreNotIn(List<String> values) {
            addCriterion("answer_score not in", values, "answerScore");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreBetween(String value1, String value2) {
            addCriterion("answer_score between", value1, value2, "answerScore");
            return (Criteria) this;
        }

        public Criteria andAnswerScoreNotBetween(String value1, String value2) {
            addCriterion("answer_score not between", value1, value2, "answerScore");
            return (Criteria) this;
        }

        public Criteria andIsBackgroundSurveyIsNull() {
            addCriterion("is_background_survey is null");
            return (Criteria) this;
        }

        public Criteria andIsBackgroundSurveyIsNotNull() {
            addCriterion("is_background_survey is not null");
            return (Criteria) this;
        }

        public Criteria andIsBackgroundSurveyEqualTo(Integer value) {
            addCriterion("is_background_survey =", value, "isBackgroundSurvey");
            return (Criteria) this;
        }

        public Criteria andIsBackgroundSurveyNotEqualTo(Integer value) {
            addCriterion("is_background_survey <>", value, "isBackgroundSurvey");
            return (Criteria) this;
        }

        public Criteria andIsBackgroundSurveyGreaterThan(Integer value) {
            addCriterion("is_background_survey >", value, "isBackgroundSurvey");
            return (Criteria) this;
        }

        public Criteria andIsBackgroundSurveyGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_background_survey >=", value, "isBackgroundSurvey");
            return (Criteria) this;
        }

        public Criteria andIsBackgroundSurveyLessThan(Integer value) {
            addCriterion("is_background_survey <", value, "isBackgroundSurvey");
            return (Criteria) this;
        }

        public Criteria andIsBackgroundSurveyLessThanOrEqualTo(Integer value) {
            addCriterion("is_background_survey <=", value, "isBackgroundSurvey");
            return (Criteria) this;
        }

        public Criteria andIsBackgroundSurveyIn(List<Integer> values) {
            addCriterion("is_background_survey in", values, "isBackgroundSurvey");
            return (Criteria) this;
        }

        public Criteria andIsBackgroundSurveyNotIn(List<Integer> values) {
            addCriterion("is_background_survey not in", values, "isBackgroundSurvey");
            return (Criteria) this;
        }

        public Criteria andIsBackgroundSurveyBetween(Integer value1, Integer value2) {
            addCriterion("is_background_survey between", value1, value2, "isBackgroundSurvey");
            return (Criteria) this;
        }

        public Criteria andIsBackgroundSurveyNotBetween(Integer value1, Integer value2) {
            addCriterion("is_background_survey not between", value1, value2, "isBackgroundSurvey");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Boolean value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Boolean value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Boolean value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Boolean value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Boolean> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Boolean> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private boolean orListValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        public Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }

        public Criterion(List<Criterion> listCriterion) {
            super();
            this.value = listCriterion;
            this.orListValue = true;
        }

        public boolean isOrListValue() {
            return orListValue;
        }
    }
}