package com.backend.survey.mapper;

import com.crm.domain.backend.survey.QuesSurveyAnsweredDetail;
import com.crm.domain.backend.survey.QuesSurveyAnsweredDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuesSurveyAnsweredDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    int countByExample(QuesSurveyAnsweredDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    int deleteByExample(QuesSurveyAnsweredDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long quesSurveyAnsweredId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    int insert(QuesSurveyAnsweredDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    int insertSelective(QuesSurveyAnsweredDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    List<QuesSurveyAnsweredDetail> selectByExample(QuesSurveyAnsweredDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    QuesSurveyAnsweredDetail selectByPrimaryKey(Long quesSurveyAnsweredId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QuesSurveyAnsweredDetail record, @Param("example") QuesSurveyAnsweredDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QuesSurveyAnsweredDetail record, @Param("example") QuesSurveyAnsweredDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuesSurveyAnsweredDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_an_ques_survey_answered_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuesSurveyAnsweredDetail record);
}