package com.backend.survey.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.crm.domain.backend.survey.QuesType;
import com.crm.domain.backend.survey.QuesTypeExample;

public interface QuesTypeMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table t_an_ques_type
     *
     * @mbggenerated
     */
    int countByExample(QuesTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table t_an_ques_type
     *
     * @mbggenerated
     */
    int deleteByExample(QuesTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table t_an_ques_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table t_an_ques_type
     *
     * @mbggenerated
     */
    int insert(QuesType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table t_an_ques_type
     *
     * @mbggenerated
     */
    int insertSelective(QuesType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table t_an_ques_type
     *
     * @mbggenerated
     */
    List<QuesType> selectByExample(QuesTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table t_an_ques_type
     *
     * @mbggenerated
     */
    QuesType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table t_an_ques_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QuesType record, @Param("example") QuesTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table t_an_ques_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QuesType record, @Param("example") QuesTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table t_an_ques_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuesType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table t_an_ques_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuesType record);
}
